/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VinylsRouteImport } from './routes/vinyls'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VinylsIndexRouteImport } from './routes/vinyls/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as VinylsVinylIdRouteImport } from './routes/vinyls.$vinylId'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'

const VinylsRoute = VinylsRouteImport.update({
  id: '/vinyls',
  path: '/vinyls',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VinylsIndexRoute = VinylsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VinylsRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const VinylsVinylIdRoute = VinylsVinylIdRouteImport.update({
  id: '/$vinylId',
  path: '/$vinylId',
  getParentRoute: () => VinylsRoute,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/$collectionId',
  path: '/$collectionId',
  getParentRoute: () => CollectionsRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/$artistId',
  path: '/$artistId',
  getParentRoute: () => ArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/vinyls': typeof VinylsRouteWithChildren
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/vinyls/$vinylId': typeof VinylsVinylIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/vinyls/': typeof VinylsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/vinyls/$vinylId': typeof VinylsVinylIdRoute
  '/artists': typeof ArtistsIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/vinyls': typeof VinylsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/vinyls': typeof VinylsRouteWithChildren
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRoute
  '/vinyls/$vinylId': typeof VinylsVinylIdRoute
  '/artists/': typeof ArtistsIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/vinyls/': typeof VinylsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/artists'
    | '/clients'
    | '/collections'
    | '/vinyls'
    | '/artists/$artistId'
    | '/clients/$clientId'
    | '/collections/$collectionId'
    | '/vinyls/$vinylId'
    | '/artists/'
    | '/clients/'
    | '/collections/'
    | '/vinyls/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artists/$artistId'
    | '/clients/$clientId'
    | '/collections/$collectionId'
    | '/vinyls/$vinylId'
    | '/artists'
    | '/clients'
    | '/collections'
    | '/vinyls'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/artists'
    | '/clients'
    | '/collections'
    | '/vinyls'
    | '/artists/$artistId'
    | '/clients/$clientId'
    | '/collections/$collectionId'
    | '/vinyls/$vinylId'
    | '/artists/'
    | '/clients/'
    | '/collections/'
    | '/vinyls/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  VinylsRoute: typeof VinylsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinyls': {
      id: '/vinyls'
      path: '/vinyls'
      fullPath: '/vinyls'
      preLoaderRoute: typeof VinylsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vinyls/': {
      id: '/vinyls/'
      path: '/'
      fullPath: '/vinyls/'
      preLoaderRoute: typeof VinylsIndexRouteImport
      parentRoute: typeof VinylsRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/vinyls/$vinylId': {
      id: '/vinyls/$vinylId'
      path: '/$vinylId'
      fullPath: '/vinyls/$vinylId'
      preLoaderRoute: typeof VinylsVinylIdRouteImport
      parentRoute: typeof VinylsRoute
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface CollectionsRouteChildren {
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsCollectionIdRoute: CollectionsCollectionIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface VinylsRouteChildren {
  VinylsVinylIdRoute: typeof VinylsVinylIdRoute
  VinylsIndexRoute: typeof VinylsIndexRoute
}

const VinylsRouteChildren: VinylsRouteChildren = {
  VinylsVinylIdRoute: VinylsVinylIdRoute,
  VinylsIndexRoute: VinylsIndexRoute,
}

const VinylsRouteWithChildren =
  VinylsRoute._addFileChildren(VinylsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  VinylsRoute: VinylsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
